function addJpegViewerInfra(generator) {
  generator.addLibrary('TFT_eSPI', '#include <TFT_eSPI.h>');
  generator.addLibrary('SD', '#include <SD.h>');
  generator.addLibrary('FS', '#include <FS.h>');
  generator.addLibrary('tjpgd', '#include "tjpgd.h"');
  generator.addLibrary('ProgJpegFull', '#include "ProgJpegFull.h"');

  let fn = '';
  fn += 'extern void epubCovRelease() __attribute__((weak));\n';
  fn += 'static const uint8_t* jpgv_jpgData;\n';
  fn += 'static int jpgv_jpgDataPos;\n';
  fn += 'static int jpgv_jpgDataLen;\n';
  fn += 'static size_t jpgv_inFunc(JDEC*, uint8_t* buf, size_t n) {\n';
  fn += '  size_t avail = jpgv_jpgDataLen - jpgv_jpgDataPos;\n';
  fn += '  if (n > avail) n = avail;\n';
  fn += '  if (buf) memcpy(buf, jpgv_jpgData + jpgv_jpgDataPos, n);\n';
  fn += '  jpgv_jpgDataPos += n;\n';
  fn += '  return n;\n';
  fn += '}\n';
  fn += 'static uint16_t* jpgv_decBuf = nullptr;\n';
  fn += 'static uint16_t* jpgv_outTarget = nullptr;\n';
  fn += 'static int jpgv_decW = 0;\n';
  fn += 'static int jpgv_decH = 0;\n';
  fn += 'static int jpgv_storeOutFunc(JDEC*, void* bitmap, JRECT* rect) {\n';
  fn += '  int16_t rw = rect->right - rect->left + 1;\n';
  fn += '  int16_t rh = rect->bottom - rect->top + 1;\n';
  fn += '  uint16_t* bmp = (uint16_t*)bitmap;\n';
  fn += '  int16_t left = rect->left;\n';
  fn += '  if (left >= jpgv_decW) return 1;\n';
  fn += '  if (left + rw > jpgv_decW) rw = jpgv_decW - left;\n';
  fn += '  for (int y = 0; y < rh; y++) {\n';
  fn += '    int dy = rect->top + y;\n';
  fn += '    if (dy >= jpgv_decH) continue;\n';
  fn += '    memcpy(&jpgv_outTarget[dy * jpgv_decW + left], &bmp[y * rw], rw * 2);\n';
  fn += '  }\n';
  fn += '  return 1;\n';
  fn += '}\n';
  fn += 'bool jpgvLastDecodeDegraded = false;\n';
  fn += 'bool espJpegDecode565(const uint8_t* jpgData, uint32_t jpgLen, int maxW, uint16_t*& outBuf, int& outW, int& outH, uint8_t _swap) {\n';
  fn += '  bool isProg = false;\n';
  fn += '  for (uint32_t ii = 2; ii + 4 < jpgLen && ii < 8192; ) {\n';
  fn += '    if (jpgData[ii] != 0xFF) { ii++; continue; }\n';
  fn += '    uint8_t mm = jpgData[ii+1];\n';
  fn += '    if (mm == 0xFF) { ii++; continue; }\n';
  fn += '    if (mm == 0xDA) break;\n';
  fn += '    if (mm == 0xC2) { isProg = true; break; }\n';
  fn += '    if (mm == 0xD8 || mm == 0xD9 || (mm >= 0xD0 && mm <= 0xD7)) { ii += 2; continue; }\n';
  fn += '    if (ii + 4 >= jpgLen) break;\n';
  fn += '    uint16_t ssl = (jpgData[ii+2] << 8) | jpgData[ii+3];\n';
  fn += '    ii += 2 + ssl;\n';
  fn += '  }\n';
  fn += '  for (int tryW = maxW; tryW >= 80; tryW /= 2) {\n';
  fn += '  if (isProg) {\n';
  fn += '    uint16_t* pBuf = nullptr; int pW = 0, pH = 0;\n';
  fn += '    if (decodeProgJpegFull((uint8_t*)jpgData, (int)jpgLen, tryW, &pBuf, &pW, &pH)) {\n';
  fn += '      outBuf = pBuf; outW = pW; outH = pH;\n';
  fn += '      return true;\n';
  fn += '    }\n';
  fn += '    Serial.printf("[JPGV] prog full decode failed (tryW=%d), fallback\\n", tryW);\n';
  fn += '    if (tryW > 320) {\n';
  fn += '      uint16_t* pBuf2 = nullptr; int pW2 = 0, pH2 = 0;\n';
  fn += '      if (decodeProgJpegFull((uint8_t*)jpgData, (int)jpgLen, 320, &pBuf2, &pW2, &pH2)) { outBuf = pBuf2; outW = pW2; outH = pH2; return true; }\n';
  fn += '    }\n';
  fn += '    jpgvLastDecodeDegraded = true;\n';
  fn += '  }\n';
  fn += '  JDEC jdec;\n';
  fn += '  uint8_t* work = (uint8_t*)ps_malloc(TJPGD_WORKSPACE_SIZE);\n';
  fn += '  if (!work) { Serial.printf("[JPGV] workspace alloc fail\\n"); return false; }\n';
  fn += '  jpgv_jpgData = jpgData; jpgv_jpgDataPos = 0; jpgv_jpgDataLen = jpgLen;\n';
  fn += '  JRESULT r = jd_prepare(&jdec, jpgv_inFunc, work, TJPGD_WORKSPACE_SIZE, nullptr);\n';
  fn += '  if (r != JDR_OK) { Serial.printf("[JPGV] prep=%d w=%d h=%d p=%d msx=%d msy=%d\\n", (int)r, jdec.width, jdec.height, jdec.progressive, jdec.msx, jdec.msy); free(work); return false; }\n';
  fn += '  int srcW = jdec.width, srcH = jdec.height;\n';
  fn += '  uint8_t scale = 0;\n';
  fn += '  while (scale < 3 && (srcW >> (scale+1)) >= tryW) scale++;\n';
  fn += '  if (jdec.progressive) scale = 3;\n';
  fn += '  outW = srcW >> scale; outH = srcH >> scale;\n';
  fn += '  outBuf = nullptr;\n';
  fn += '  outBuf = (uint16_t*)ps_malloc((size_t)outW * outH * 2);\n';
  fn += '  if (!outBuf) { Serial.printf("[JPGV] decBuf alloc fail %dx%d (tryW=%d), shrink\\n", outW, outH, tryW); free(work); jpgvLastDecodeDegraded = true; continue; }\n';
  fn += '  memset(outBuf, 0, (size_t)outW * outH * 2);\n';
  fn += '  jpgv_outTarget = outBuf; jpgv_decW = outW; jpgv_decH = outH;\n';
  fn += '  jdec.swap = _swap;\n';
  fn += '  JRESULT r2 = jd_decomp(&jdec, jpgv_storeOutFunc, scale);\n';
  fn += '  if (r2 != JDR_OK) { Serial.printf("[JPGV] decomp fail=%d\\n", (int)r2); free(outBuf); outBuf = nullptr; jpgv_outTarget = nullptr; }\n';
  fn += '  free(work);\n';
  fn += '  if (r2 != JDR_OK) return false;\n';
  fn += '  if (jdec.progressive) jpgvLastDecodeDegraded = true;\n';
  fn += '  return true;\n';
  fn += '  }\n';
  fn += '  Serial.printf("[JPGV] all decode attempts failed\\n");\n';
  fn += '  return false;\n';
  fn += '}\n';
  fn += 'extern void epubFontRelease() __attribute__((weak));\n';
  fn += 'extern void epubFontRestore() __attribute__((weak));\n';
  fn += 'static int jpgv_imgW = 0;\n';
  fn += 'static int jpgv_imgH = 0;\n';
  fn += 'static int jpgv_viewY = 0;\n';
  fn += 'static int jpgv_zoom = 0;\n';
  fn += 'static int jpgv_zoomX = 0;\n';
  fn += 'static int jpgv_zoomY = 0;\n';
  fn += 'static int jpgv_grid = 0;\n';
  fn += 'static int jpgv_gridCols = 0;\n';
  fn += 'static int jpgv_gridRows = 0;\n';
  fn += 'static int jpgv_cellIdx = 0;\n';
  fn += 'static int jpgv_gridRTL = 1;\n';
  fn += 'static int jpgv_rowsPerPage = 1;\n';
  fn += 'static int jpgv_keepZoom = 0;\n';
  fn += 'static String jpgv_path;\n';
  fn += 'static void jpgv_renderView() {\n';
  fn += '  int scrW = tft.width();\n';
  fn += '  int scrH = tft.height();\n';
  fn += '  static uint16_t* frm = nullptr;\n';
  fn += '  if (!frm) frm = (uint16_t*)ps_malloc((size_t)scrW * scrH * 2);\n';
  fn += '  if (frm && jpgv_decBuf && jpgv_imgW > 0) {\n';
  fn += '    if (jpgv_zoom) {\n';
  fn += '      int maxX = jpgv_imgW - scrW; if (maxX < 0) maxX = 0;\n';
  fn += '      int maxY = jpgv_imgH - scrH; if (maxY < 0) maxY = 0;\n';
  fn += '      if (jpgv_zoomX > maxX) jpgv_zoomX = maxX; if (jpgv_zoomX < 0) jpgv_zoomX = 0;\n';
  fn += '      if (jpgv_zoomY > maxY) jpgv_zoomY = maxY; if (jpgv_zoomY < 0) jpgv_zoomY = 0;\n';
  fn += '      for (int y = 0; y < scrH; y++) {\n';
  fn += '        uint16_t* drow = &frm[(size_t)y * scrW];\n';
  fn += '        int sy = jpgv_zoomY + y;\n';
  fn += '        if (sy >= jpgv_imgH) { for (int x = 0; x < scrW; x++) drow[x] = 0; continue; }\n';
  fn += '        const uint16_t* srow = &jpgv_decBuf[(size_t)sy * jpgv_imgW];\n';
  fn += '        for (int x = 0; x < scrW; x++) { int sx = jpgv_zoomX + x; drow[x] = (sx < jpgv_imgW) ? srow[sx] : 0; }\n';
  fn += '      }\n';
  fn += '    } else {\n';
  fn += '      int maxY = jpgv_imgH - jpgv_rowsPerPage; if (maxY < 0) maxY = 0;\n';
  fn += '      if (jpgv_viewY > maxY) jpgv_viewY = maxY; if (jpgv_viewY < 0) jpgv_viewY = 0;\n';
  fn += '      for (int y = 0; y < scrH; y++) {\n';
  fn += '        uint16_t* drow = &frm[(size_t)y * scrW];\n';
  fn += '        int y0 = jpgv_viewY + (int)((long)y * jpgv_rowsPerPage / scrH);\n';
  fn += '        int y1 = jpgv_viewY + (int)((long)(y + 1) * jpgv_rowsPerPage / scrH);\n';
  fn += '        if (y1 >= jpgv_imgH) y1 = jpgv_imgH - 1;\n';
  fn += '        if (y1 < y0) y1 = y0;\n';
  fn += '        const uint16_t* srow = &jpgv_decBuf[(size_t)y0 * jpgv_imgW];\n';
  fn += '        const uint16_t* srow2 = (y1 > y0) ? &jpgv_decBuf[(size_t)y1 * jpgv_imgW] : srow;\n';
  fn += '        for (int x = 0; x < scrW; x++) {\n';
  fn += '          int x0 = (int)((long)x * jpgv_imgW / scrW);\n';
  fn += '          int x1 = (int)((long)(x + 1) * jpgv_imgW / scrW);\n';
  fn += '          if (x1 >= jpgv_imgW) x1 = jpgv_imgW - 1;\n';
  fn += '          if (x1 < x0) x1 = x0;\n';
  fn += '          uint32_t r = 0, g = 0, b = 0, n = 0;\n';
  fn += '          for (int yy = y0; yy <= y1; yy++) {\n';
  fn += '            const uint16_t* rr = (yy == y0) ? srow : ((yy == y1) ? srow2 : &jpgv_decBuf[(size_t)yy * jpgv_imgW]);\n';
  fn += '            for (int xx = x0; xx <= x1; xx++) { uint16_t q = (uint16_t)((rr[xx] >> 8) | (rr[xx] << 8)); r += (q >> 11) & 0x1F; g += (q >> 5) & 0x3F; b += q & 0x1F; n++; }\n';
  fn += '          }\n';
  fn += '          if (n) { uint16_t v = (uint16_t)(((r / n) << 11) | ((g / n) << 5) | (b / n)); drow[x] = (uint16_t)((v >> 8) | (v << 8)); }\n';
  fn += '        }\n';
  fn += '      }\n';
  fn += '    }\n';
  fn += '    tft.pushImage(0, 0, scrW, scrH, frm);\n';
  fn += '  } else {\n';
  fn += '    tft.fillRect(0, 0, scrW, scrH, TFT_BLACK);\n';
  fn += '  }\n';
  fn += '  if (jpgv_zoom) {\n';
  fn += '    tft.fillRoundRect(4, scrH - 20, 34, 17, 4, 0x0000);\n';
  fn += '    tft.drawRoundRect(4, scrH - 20, 34, 17, 4, 0x07FF);\n';
  fn += '    tft.setTextColor(0x07FF, 0x0000); tft.setTextSize(1); tft.setCursor(10, scrH - 16); tft.print(jpgv_grid ? (jpgv_gridRTL ? "G<" : "G>") : "1:1");\n';
  fn += '    if (jpgv_grid && jpgv_gridCols > 0 && jpgv_gridRows > 0 && jpgv_decBuf) {\n';
  fn += '      int mw = 32, mh = mw * scrH / scrW; if (mh < 22) { mh = 22; mw = mh * scrW / scrH; }\n';
  fn += '      int mx = scrW - mw - 6, my = scrH - mh - 6;\n';
  fn += '      tft.fillRoundRect(mx - 4, my - 2, mw + 8, mh + 8, 5, 0x0000);\n';
  fn += '      static uint16_t* thumbBuf = nullptr;\n';
  fn += '      if (!thumbBuf) thumbBuf = (uint16_t*)ps_malloc(64 * 64 * 2);\n';
  fn += '      if (thumbBuf) {\n';
  fn += '        for (int ty = 0; ty < mh; ty++) {\n';
  fn += '          int sy = ty * jpgv_imgH / mh; if (sy >= jpgv_imgH) sy = jpgv_imgH - 1;\n';
  fn += '          const uint16_t* srow = &jpgv_decBuf[(size_t)sy * jpgv_imgW];\n';
  fn += '          uint16_t* drow = &thumbBuf[ty * mw];\n';
  fn += '          for (int tx = 0; tx < mw; tx++) { int sx = tx * jpgv_imgW / mw; if (sx >= jpgv_imgW) sx = jpgv_imgW - 1; drow[tx] = srow[sx]; }\n';
  fn += '        }\n';
  fn += '        tft.pushImage(mx, my, mw, mh, thumbBuf);\n';
  fn += '      } else { tft.fillRect(mx, my, mw, mh, 0x0000); }\n';
  fn += '      tft.drawRoundRect(mx - 3, my - 3, mw + 6, mh + 6, 4, 0x7BCF);\n';
  fn += '      for (int r = 1; r < jpgv_gridRows; r++) { int yy = my + r * mh / jpgv_gridRows; tft.drawFastHLine(mx, yy, mw, 0x2124); }\n';
  fn += '      for (int c = 1; c < jpgv_gridCols; c++) { int xx = mx + c * mw / jpgv_gridCols; tft.drawFastVLine(xx, my, mh, 0x2124); }\n';
  fn += '      int cr = jpgv_cellIdx / jpgv_gridCols, cc = jpgv_cellIdx % jpgv_gridCols;\n';
  fn += '      if (jpgv_gridRTL) cc = jpgv_gridCols - 1 - cc;\n';
  fn += '      int cx = mx + cc * mw / jpgv_gridCols, cy = my + cr * mh / jpgv_gridRows;\n';
  fn += '      int cw = mw / jpgv_gridCols, ch = mh / jpgv_gridRows;\n';
  fn += '      tft.fillRoundRect(cx + 1, cy + 1, cw - 2, ch - 2, 2, 0x5800);\n';
  fn += '      tft.drawRoundRect(cx + 1, cy + 1, cw - 2, ch - 2, 2, 0xFDA0);\n';
  fn += '    }\n';
  fn += '  }\n';
  fn += '  { int sl = jpgv_path.lastIndexOf("/"); String fn0 = (sl >= 0) ? jpgv_path.substring(sl + 1) : jpgv_path;\n';
  fn += '    tft.setTextSize(1); int tw = tft.textWidth(fn0);\n';
  fn += '    tft.fillRoundRect((scrW - tw - 14) / 2, scrH - 20, tw + 14, 17, 4, 0x0000);\n';
  fn += '    tft.drawRoundRect((scrW - tw - 14) / 2, scrH - 20, tw + 14, 17, 4, 0x4208);\n';
  fn += '    tft.setTextColor(0xC618, 0x0000); tft.setCursor((scrW - tw) / 2, scrH - 16); tft.print(fn0);\n';
  fn += '  }\n';
  fn += '}\n';
  fn += 'static int jpgv_stops[64];\n';
  fn += 'static int jpgv_stopCount = 0;\n';
  fn += 'static int jpgv_stopIdx = 0;\n';
  fn += 'static void jpgv_computeStops(int totalH, int scrH) {\n';
  fn += '  jpgv_stopCount = 0;\n';
  fn += '  if (totalH <= scrH || scrH < 1) { jpgv_stops[0] = 0; jpgv_stopCount = 1; return; }\n';
  fn += '  int maxY = totalH - scrH;\n';
  fn += '  int halfH = scrH / 2;\n';
  fn += '  jpgv_stops[jpgv_stopCount++] = 0;\n';
  fn += '  if (halfH >= maxY) { jpgv_stops[jpgv_stopCount++] = maxY; }\n';
  fn += '  else {\n';
  fn += '    jpgv_stops[jpgv_stopCount++] = halfH;\n';
  fn += '    int y = halfH;\n';
  fn += '    while (jpgv_stopCount < 64) {\n';
  fn += '      y += scrH;\n';
  fn += '      if (y >= maxY) { jpgv_stops[jpgv_stopCount++] = maxY; break; }\n';
  fn += '      jpgv_stops[jpgv_stopCount++] = y;\n';
  fn += '    }\n';
  fn += '  }\n';
  fn += '}\n';
  fn += 'static int jpgv_scrollY = 0;\n';
  fn += 'static String jpgv_numPath(const String& cur, int delta) {\n';
  fn += '  int sl = cur.lastIndexOf(\'/\');\n';
  fn += '  String dirp = (sl >= 0) ? cur.substring(0, sl + 1) : "/";\n';
  fn += '  String fle = (sl >= 0) ? cur.substring(sl + 1) : cur;\n';
  fn += '  int ns = 0;\n';
  fn += '  while (ns < (int)fle.length() && (fle[ns] < \'0\' || fle[ns] > \'9\')) ns++;\n';
  fn += '  int ne = ns;\n';
  fn += '  while (ne < (int)fle.length() && (fle[ne] >= \'0\' && fle[ne] <= \'9\')) ne++;\n';
  fn += '  if (ns == ne) return "";\n';
  fn += '  String prefix = fle.substring(0, ns);\n';
  fn += '  long num = fle.substring(ns, ne).toInt();\n';
  fn += '  int numDigits = ne - ns;\n';
  fn += '  String suffix = fle.substring(ne);\n';
  fn += '  num += delta;\n';
  fn += '  if (num < 0) return "";\n';
  fn += '  String numStr = String(num);\n';
  fn += '  while ((int)numStr.length() < numDigits) numStr = "0" + numStr;\n';
  fn += '  String np = dirp + prefix + numStr + suffix;\n';
  fn += '  if (SD.exists(np)) return np;\n';
  fn += '  return "";\n';
  fn += '}\n';
  fn += 'static uint32_t jpgv_rd32(const uint8_t* p) { return (uint32_t)p[0]|((uint32_t)p[1]<<8)|((uint32_t)p[2]<<16)|((uint32_t)p[3]<<24); }\n';
  fn += 'static uint16_t jpgv_rd16(const uint8_t* p) { return (uint16_t)((uint16_t)p[0]|((uint16_t)p[1]<<8)); }\n';
  fn += 'static bool jpgv_decodeBmp(uint8_t* data, int sz) {\n';
  fn += '  if (sz < 54 || data[0] != 0x42 || data[1] != 0x4D) return false;\n';
  fn += '  uint32_t pixelOffset = jpgv_rd32(data + 10);\n';
  fn += '  int32_t bmpW = (int32_t)jpgv_rd32(data + 18);\n';
  fn += '  int32_t bmpH = (int32_t)jpgv_rd32(data + 22);\n';
  fn += '  uint16_t bpp = jpgv_rd16(data + 28);\n';
  fn += '  uint32_t compression = jpgv_rd32(data + 30);\n';
  fn += '  if (compression != 0 || (bpp != 24 && bpp != 32)) return false;\n';
  fn += '  if (bmpW <= 0) return false;\n';
  fn += '  bool topDown = (bmpH < 0);\n';
  fn += '  int absH = topDown ? -bmpH : bmpH;\n';
  fn += '  int bypp = bpp / 8;\n';
  fn += '  int rowSize = ((bmpW * bypp + 3) & ~3);\n';
  fn += '  if ((int)pixelOffset + rowSize * absH > sz) return false;\n';
  fn += '  if (jpgv_decBuf) { free(jpgv_decBuf); jpgv_decBuf = nullptr; }\n';
  fn += '  jpgv_decBuf = (uint16_t*)ps_malloc((size_t)bmpW * absH * 2);\n';
  fn += '  if (!jpgv_decBuf) return false;\n';
  fn += '  jpgv_decW = bmpW; jpgv_decH = absH;\n';
  fn += '  for (int y = 0; y < absH; y++) {\n';
  fn += '    int srcY = topDown ? y : (absH - 1 - y);\n';
  fn += '    uint8_t* row = data + pixelOffset + (size_t)srcY * rowSize;\n';
  fn += '    for (int x = 0; x < bmpW; x++) {\n';
  fn += '      uint8_t b = row[x * bypp];\n';
  fn += '      uint8_t g = row[x * bypp + 1];\n';
  fn += '      uint8_t r = row[x * bypp + 2];\n';
  fn += '      { uint16_t v = ((uint16_t)(r >> 3) << 11) | ((uint16_t)(g >> 2) << 5) | (b >> 3); jpgv_decBuf[y * bmpW + x] = (uint16_t)((v >> 8) | (v << 8)); }\n';
  fn += '    }\n';
  fn += '  }\n';
  fn += '  return true;\n';
  fn += '}\n';
  fn += 'static void jpgv_gridBuild();\n';
  fn += 'static void jpgv_gridCell(int idx, int& x0, int& y0);\n';
  fn += 'static bool jpgv_show(const String& path) {\n';
  fn += '  int kz = jpgv_keepZoom;\n';
  fn += '  jpgv_keepZoom = 0;\n';
  fn += '  String lower = path; lower.toLowerCase();\n';
  fn += '  bool isBmp = lower.endsWith(".bmp");\n';
  fn += '  File f = SD.open(path, FILE_READ);\n';
  fn += '  if (!f) { tft.fillRoundRect(8,8,tft.width()-16,22,6,0x0000); tft.drawRoundRect(8,8,tft.width()-16,22,6,0xF800); tft.setTextColor(0xF800,0x0000); tft.setCursor(14,16); tft.print("Cannot open file"); delay(1500); return false; }\n';
  fn += '  int sz = f.size();\n';
  fn += '  if (epubCovRelease) epubCovRelease();\n';
  fn += '  if (epubFontRelease) epubFontRelease();\n';
  fn += '  uint8_t* fileBuf = (uint8_t*)ps_malloc(sz + 16);\n';
  fn += '  if (!fileBuf) { f.close(); tft.fillRoundRect(8,8,tft.width()-16,22,6,0x0000); tft.drawRoundRect(8,8,tft.width()-16,22,6,0xF800); tft.setTextColor(0xF800,0x0000); tft.setCursor(14,16); tft.printf("Too big: %d KB (free %uK)", sz/1024, (unsigned)(ESP.getFreePsram()/1024)); delay(1500); return false; }\n';
  fn += '  int rd = 0;\n';
  fn += '  int stallCount = 0;\n';
  fn += '  while (rd < sz) {\n';
  fn += '    int want = sz - rd; if (want > 8192) want = 8192;\n';
  fn += '    int n = f.read(fileBuf + rd, want);\n';
  fn += '    if (n <= 0) {\n';
  fn += '      Serial.printf("[JPGV] stall at %d/%d #%d\\n", rd, sz, stallCount);\n';
  fn += '      f.close(); delay(100); sdfatReinit();\n';
  fn += '      f = SD.open(path, FILE_READ);\n';
  fn += '      if (!f) { if (++stallCount > 5) break; delay(200); continue; }\n';
  fn += '      f.seek(rd);\n';
  fn += '      if (++stallCount > 10) break;\n';
  fn += '      continue;\n';
  fn += '    }\n';
  fn += '    rd += n; stallCount = 0;\n';
  fn += '  }\n';
  fn += '  f.close();\n';
  fn += '  if (rd != sz) { Serial.printf("[JPGV] read FAIL rd=%d/%d\\n", rd, sz); free(fileBuf); tft.fillRoundRect(8,8,tft.width()-16,22,6,0x0000); tft.drawRoundRect(8,8,tft.width()-16,22,6,0xF800); tft.setTextColor(0xF800,0x0000); tft.setCursor(14,16); tft.printf("SD read fail %d/%d", rd, sz); delay(1500); return false; }\n';
  fn += '  if (jpgv_decBuf) { free(jpgv_decBuf); jpgv_decBuf = nullptr; }\n';
  fn += '  int decW = 0, decH = 0;\n';
  fn += '  if (isBmp) {\n';
  fn += '    if (!jpgv_decodeBmp(fileBuf, sz)) { free(fileBuf); tft.fillRoundRect(8,8,tft.width()-16,22,6,0x0000); tft.drawRoundRect(8,8,tft.width()-16,22,6,0xF800); tft.setTextColor(0xF800,0x0000); tft.setCursor(14,16); tft.print("BMP decode fail"); delay(1500); return false; }\n';
  fn += '    free(fileBuf);\n';
  fn += '    decW = jpgv_decW; decH = jpgv_decH;\n';
  fn += '  } else {\n';
  fn += '    int scrW0 = tft.width();\n';
  fn += '    if (!espJpegDecode565(fileBuf, sz, scrW0 * 2, jpgv_decBuf, decW, decH, 1)) { free(fileBuf); tft.fillRoundRect(8,8,tft.width()-16,22,6,0x0000); tft.drawRoundRect(8,8,tft.width()-16,22,6,0xF800); tft.setTextColor(0xF800,0x0000); tft.setCursor(14,16); tft.print("JPEG decode fail"); delay(1500); return false; }\n';
  fn += '    jpgv_decW = decW; jpgv_decH = decH;\n';
  fn += '    free(fileBuf);\n';
  fn += '  }\n';
  fn += '  int scrW = tft.width();\n';
  fn += '  jpgv_imgW = decW; jpgv_imgH = decH;\n';
  fn += '  jpgv_rowsPerPage = (int)((long)tft.height() * decW / scrW);\n';
  fn += '  if (jpgv_rowsPerPage < 1) jpgv_rowsPerPage = 1;\n';
  fn += '  jpgv_viewY = 0;\n';
  fn += '  jpgv_zoom = 0; jpgv_zoomX = 0; jpgv_zoomY = 0; jpgv_grid = 0; jpgv_cellIdx = 0;\n';
  fn += '  jpgv_scrollY = 0;\n';
  fn += '  jpgv_computeStops(jpgv_imgH, jpgv_rowsPerPage);\n';
  fn += '  jpgv_stopIdx = 0;\n';
  fn += '  jpgv_path = path;\n';
  fn += '  if (kz != 0) {\n';
  fn += '    jpgv_zoom = 1;\n';
  fn += '    jpgv_gridBuild();\n';
  fn += '    if (jpgv_grid && jpgv_gridCols > 0 && jpgv_gridRows > 0) {\n';
  fn += '      int total = jpgv_gridCols * jpgv_gridRows;\n';
  fn += '      jpgv_cellIdx = (kz > 0) ? 0 : (total - 1);\n';
  fn += '      jpgv_gridCell(jpgv_cellIdx, jpgv_zoomX, jpgv_zoomY);\n';
  fn += '    } else { jpgv_zoomX = 0; jpgv_zoomY = 0; }\n';
  fn += '  }\n';
  fn += '  jpgv_renderView();\n';
  fn += '  return true;\n';
  fn += '}\n';
  fn += 'static void jpgv_gridBuild() {\n';
  fn += '  jpgv_grid = 0; jpgv_gridCols = 0; jpgv_gridRows = 0; jpgv_cellIdx = 0;\n';
  fn += '  if (jpgv_imgW <= 0 || jpgv_imgH <= 0) return;\n';
  fn += '  int scrW = tft.width(), scrH = tft.height();\n';
  fn += '  jpgv_gridCols = (jpgv_imgW + scrW - 1) / scrW;\n';
  fn += '  jpgv_gridRows = (jpgv_imgH + scrH - 1) / scrH;\n';
  fn += '  if (jpgv_gridCols < 1) jpgv_gridCols = 1;\n';
  fn += '  if (jpgv_gridRows < 1) jpgv_gridRows = 1;\n';
  fn += '  if (jpgv_gridCols == 1 && jpgv_gridRows == 1) return;\n';
  fn += '  jpgv_grid = 1;\n';
  fn += '}\n';
  fn += 'static void jpgv_gridCell(int idx, int& x0, int& y0) {\n';
  fn += '  int scrW = tft.width(), scrH = tft.height();\n';
  fn += '  int r = idx / jpgv_gridCols, c = idx % jpgv_gridCols;\n';
  fn += '  if (jpgv_gridRTL) c = jpgv_gridCols - 1 - c;\n';
  fn += '  x0 = c * scrW;\n';
  fn += '  int maxX = jpgv_imgW - scrW; if (maxX < 0) maxX = 0;\n';
  fn += '  if (x0 > maxX) x0 = maxX;\n';
  fn += '  y0 = r * scrH;\n';
  fn += '  int maxY = jpgv_imgH - scrH; if (maxY < 0) maxY = 0;\n';
  fn += '  if (y0 > maxY) y0 = maxY;\n';
  fn += '}\n';
  fn += 'static void jpgv_zoomToggle() {\n';
  fn += '  jpgv_zoom = !jpgv_zoom;\n';
  fn += '  int scrW = tft.width(), scrH = tft.height();\n';
  fn += '  if (jpgv_zoom) {\n';
  fn += '    jpgv_gridBuild();\n';
  fn += '    if (jpgv_grid) {\n';
  fn += '      jpgv_zoomX = 0; jpgv_zoomY = 0;\n';
  fn += '      jpgv_gridCell(0, jpgv_zoomX, jpgv_zoomY);\n';
  fn += '    } else {\n';
  fn += '    int maxX = jpgv_imgW - scrW; if (maxX < 0) maxX = 0;\n';
  fn += '    int maxY = jpgv_imgH - scrH; if (maxY < 0) maxY = 0;\n';
  fn += '    jpgv_zoomX = maxX / 2;\n';
  fn += '    jpgv_zoomY = jpgv_viewY + (jpgv_rowsPerPage - scrH) / 2;\n';
  fn += '    if (jpgv_zoomY > maxY) jpgv_zoomY = maxY; if (jpgv_zoomY < 0) jpgv_zoomY = 0;\n';
  fn += '    }\n';
  fn += '  } else {\n';
  fn += '    jpgv_viewY = (int)(((long)jpgv_zoomY + jpgv_rowsPerPage / 2) / jpgv_rowsPerPage) * jpgv_rowsPerPage;\n';
  fn += '    int maxY = jpgv_imgH - jpgv_rowsPerPage; if (maxY < 0) maxY = 0;\n';
  fn += '    if (jpgv_viewY > maxY) jpgv_viewY = maxY; if (jpgv_viewY < 0) jpgv_viewY = 0;\n';
  fn += '    jpgv_computeStops(jpgv_imgH, jpgv_rowsPerPage);\n';
  fn += '    int best = 0, bd = 1 << 30;\n';
  fn += '    for (int i = 0; i < jpgv_stopCount; i++) { int d = jpgv_stops[i] - jpgv_viewY; if (d < 0) d = -d; if (d < bd) { bd = d; best = i; } }\n';
  fn += '    if (jpgv_stopCount > 0) { jpgv_stopIdx = best; jpgv_scrollY = jpgv_stops[best]; jpgv_viewY = jpgv_scrollY; }\n';
  fn += '  }\n';
  fn += '  jpgv_renderView();\n';
  fn += '}\n';
  fn += 'static void jpgv_pan(int dx, int dy) {\n';
  fn += '  if (!jpgv_zoom || !jpgv_decBuf) return;\n';
  fn += '  int scrW = tft.width(), scrH = tft.height();\n';
  fn += '  int maxX = jpgv_imgW - scrW; if (maxX < 0) maxX = 0;\n';
  fn += '  int maxY = jpgv_imgH - scrH; if (maxY < 0) maxY = 0;\n';
  fn += '  jpgv_zoomX += dx * scrW; if (jpgv_zoomX > maxX) jpgv_zoomX = maxX; if (jpgv_zoomX < 0) jpgv_zoomX = 0;\n';
  fn += '  jpgv_zoomY += dy * scrH; if (jpgv_zoomY > maxY) jpgv_zoomY = maxY; if (jpgv_zoomY < 0) jpgv_zoomY = 0;\n';
  fn += '  jpgv_renderView();\n';
  fn += '}\n';
  fn += 'static bool jpgv_toggleRTL() {\n';
  fn += '  if (!jpgv_zoom) return false;\n';
  fn += '  jpgv_gridRTL = !jpgv_gridRTL;\n';
  fn += '  if (jpgv_grid && jpgv_gridCols > 0) {\n';
  fn += '    int r = jpgv_cellIdx / jpgv_gridCols;\n';
  fn += '    int c = jpgv_cellIdx % jpgv_gridCols;\n';
  fn += '    jpgv_cellIdx = r * jpgv_gridCols + (jpgv_gridCols - 1 - c);\n';
  fn += '    jpgv_gridCell(jpgv_cellIdx, jpgv_zoomX, jpgv_zoomY);\n';
  fn += '  }\n';
  fn += '  jpgv_renderView();\n';
  fn += '  return true;\n';
  fn += '}\n';
  fn += 'static bool jpgv_cellStep(int dir) {\n';
  fn += '  if (!jpgv_grid) return false;\n';
  fn += '  int total = jpgv_gridCols * jpgv_gridRows;\n';
  fn += '  jpgv_cellIdx += dir;\n';
  fn += '  if (jpgv_cellIdx >= total) {\n';
  fn += '    jpgv_cellIdx = total - 1;\n';
  fn += '    String next = jpgv_numPath(jpgv_path, 1);\n';
  fn += '    jpgv_keepZoom = 1;\n';
  fn += '    if (next.length() > 0 && jpgv_show(next)) return true;\n';
  fn += '    jpgv_renderView(); return true;\n';
  fn += '  }\n';
  fn += '  if (jpgv_cellIdx < 0) {\n';
  fn += '    jpgv_cellIdx = 0;\n';
  fn += '    String prev = jpgv_numPath(jpgv_path, -1);\n';
  fn += '    jpgv_keepZoom = -1;\n';
  fn += '    if (prev.length() > 0 && jpgv_show(prev)) return true;\n';
  fn += '    jpgv_renderView(); return true;\n';
  fn += '  }\n';
  fn += '  jpgv_gridCell(jpgv_cellIdx, jpgv_zoomX, jpgv_zoomY);\n';
  fn += '  jpgv_renderView();\n';
  fn += '  return true;\n';
  fn += '}\n';
  fn += 'static bool jpgv_next() {\n';
  fn += '  if (jpgv_zoom && jpgv_decBuf) {\n';
  fn += '    if (jpgv_grid) return jpgv_cellStep(1);\n';
  fn += '    int scrH = tft.height();\n';
  fn += '    int step = scrH * 3 / 4;\n';
  fn += '    int maxY = jpgv_imgH - scrH; if (maxY < 0) maxY = 0;\n';
  fn += '    jpgv_zoomY += step; if (jpgv_zoomY > maxY) jpgv_zoomY = maxY;\n';
  fn += '    jpgv_renderView(); return true;\n';
  fn += '  }\n';
  fn += '  if (jpgv_stopCount <= 0) return false;\n';
  fn += '  jpgv_stopIdx++;\n';
  fn += '  if (jpgv_stopIdx >= jpgv_stopCount) {\n';
  fn += '    jpgv_stopIdx = jpgv_stopCount - 1;\n';
  fn += '    String next = jpgv_numPath(jpgv_path, 1);\n';
  fn += '    if (next.length() > 0) { if (jpgv_show(next)) return true; jpgv_renderView(); return true; }\n';
  fn += '    return true;\n';
  fn += '  }\n';
  fn += '  jpgv_scrollY = jpgv_stops[jpgv_stopIdx];\n';
  fn += '  jpgv_viewY = jpgv_scrollY;\n';
  fn += '  jpgv_renderView();\n';
  fn += '  return true;\n';
  fn += '}\n';
  fn += 'static bool jpgv_prev() {\n';
  fn += '  if (jpgv_zoom && jpgv_decBuf) {\n';
  fn += '    if (jpgv_grid) return jpgv_cellStep(-1);\n';
  fn += '    int scrH = tft.height();\n';
  fn += '    int step = scrH * 3 / 4;\n';
  fn += '    jpgv_zoomY -= step; if (jpgv_zoomY < 0) jpgv_zoomY = 0;\n';
  fn += '    jpgv_renderView(); return true;\n';
  fn += '  }\n';
  fn += '  if (jpgv_stopCount <= 0) return false;\n';
  fn += '  jpgv_stopIdx--;\n';
  fn += '  if (jpgv_stopIdx < 0) {\n';
  fn += '    jpgv_stopIdx = 0;\n';
  fn += '    String prev = jpgv_numPath(jpgv_path, -1);\n';
  fn += '    if (prev.length() > 0) {\n';
  fn += '      if (jpgv_show(prev)) {\n';
  fn += '        jpgv_stopIdx = jpgv_stopCount - 1;\n';
  fn += '        jpgv_scrollY = jpgv_stops[jpgv_stopIdx];\n';
  fn += '        jpgv_viewY = jpgv_scrollY;\n';
  fn += '      }\n';
  fn += '      jpgv_renderView();\n';
  fn += '      return true;\n';
  fn += '    }\n';
  fn += '    jpgv_scrollY = 0; jpgv_viewY = 0;\n';
  fn += '    jpgv_renderView();\n';
  fn += '    return true;\n';
  fn += '  }\n';
  fn += '  jpgv_scrollY = jpgv_stops[jpgv_stopIdx];\n';
  fn += '  jpgv_viewY = jpgv_scrollY;\n';
  fn += '  jpgv_renderView();\n';
  fn += '  return true;\n';
  fn += '}\n';
  fn += 'static void jpgv_exit() {\n';
  fn += '  if (jpgv_decBuf) { free(jpgv_decBuf); jpgv_decBuf = nullptr; }\n';
  fn += '  jpgv_imgW = 0; jpgv_imgH = 0; jpgv_viewY = 0; jpgv_scrollY = 0; jpgv_zoom = 0; jpgv_zoomX = 0; jpgv_zoomY = 0; jpgv_rowsPerPage = 1;\n';
  fn += '  jpgv_stopIdx = 0; jpgv_stopCount = 0;\n';
  fn += '  jpgv_path = "";\n';
  fn += '  if (epubFontRestore) epubFontRestore();\n';
  fn += '}\n';
  generator.addFunction('jpgvInfra', fn);
}

Arduino.forBlock['sd_jpg_viewer_open'] = function(block, generator) {
  const path = generator.valueToCode(block, 'PATH', generator.ORDER_ATOMIC) || '""';
  addJpegViewerInfra(generator);
  return ['jpgv_show(String(' + path + '))', generator.ORDER_ATOMIC];
};

Arduino.forBlock['sd_jpg_viewer_next'] = function(block, generator) {
  addJpegViewerInfra(generator);
  return ['jpgv_next()', generator.ORDER_ATOMIC];
};

Arduino.forBlock['sd_jpg_viewer_prev'] = function(block, generator) {
  addJpegViewerInfra(generator);
  return ['jpgv_prev()', generator.ORDER_ATOMIC];
};

Arduino.forBlock['sd_jpg_viewer_zoom'] = function(block, generator) {
  addJpegViewerInfra(generator);
  return 'jpgv_zoomToggle();\n';
};

Arduino.forBlock['sd_jpg_viewer_pan'] = function(block, generator) {
  const dx = generator.valueToCode(block, 'DX', generator.ORDER_ATOMIC) || '0';
  const dy = generator.valueToCode(block, 'DY', generator.ORDER_ATOMIC) || '0';
  addJpegViewerInfra(generator);
  return 'jpgv_pan(' + dx + ', ' + dy + ');\n';
};

Arduino.forBlock['sd_jpg_viewer_dir'] = function(block, generator) {
  addJpegViewerInfra(generator);
  return ['jpgv_toggleRTL()', generator.ORDER_ATOMIC];
};

Arduino.forBlock['sd_jpg_viewer_exit'] = function(block, generator) {
  addJpegViewerInfra(generator);
  return 'jpgv_exit();\n';
};
